issue:
  opened:
    addLabels:
      - honeybee
      - legacy
      - triage
  closed:
    addLabels:
      - done

pull_request:
  opened:
    addLabels:
      - honeybee
      - legacy
  closed:
    addLabels:
      - done

projects:  
  - name: Global Kanban
    type: org
    issue_type: issue
    columns:
      - name: triage
        labels:
          - triage
        actions:
          removeLabels:
            - backlog
            - todo
            - in progress
            - done 
      - name: backlog
        labels:
          - backlog
        actions:
          removeLabels:
            - triage
            - todo
            - in progress
            - done 
      - name: todo
        labels:
          - todo
        actions:
          removeLabels:
            - triage
            - backlog
            - in progress
            - done 
      - name: in progress
        labels:
          - in progress
        actions:
          removeLabels:
            - triage
            - todo
            - backlog
            - done
      - name: done
        labels:
          - done 
        actions:
          removeLabels:
            - triage
            - backlog
            - todo
            - in progress

  - name: Hacktoberfest
    type: org
    issue_type: issue
    label: hacktoberfest
    columns: 
      - name: ladybug
        labels:
          - hacktoberfest
      - name: done
        labels:
          - done

labels:
- name: honeybee
  color: "#FFFB00"
- name: legacy
  color: "#0075CA"

- name: in progress
  color: "#EDEDED"
- name: triage
  color: "#EDEDED"
- name: todo
  color: "#EDEDED"
- name: backlog
  color: "#EDEDED"
- name: done
  color: "#EDEDED"

- name: hacktoberfest
  color: "#802AC1"
