# By Mostapha Sadeghipour Roudsari
# Sadeghipour@gmail.com
# Honeybee started by Mostapha Sadeghipour Roudsari is licensed
# under a Creative Commons Attribution-ShareAlike 3.0 Unported License.

"""
Daysim's electrical lighting use

-
Provided by Honeybee 0.0.56

    Args:
        _htmlReport: Address to a valid .htm file generated by daysim.
    Returns:
        electricLightingUse: Lists of annual occupancy profiles if any
"""
ghenv.Component.Name = "Honeybee_Daysim Electrical Lighting Use"
ghenv.Component.NickName = 'DSElectricalLightingUse'
ghenv.Component.Message = 'VER 0.0.56\nAPR_05_2015'
ghenv.Component.Category = "Honeybee"
ghenv.Component.SubCategory = "04 | Daylight | Daylight"
#compatibleHBVersion = VER 0.0.56\nFEB_01_2015
#compatibleLBVersion = VER 0.0.59\nFEB_01_2015
try: ghenv.Component.AdditionalHelpFromDocStrings = "5"
except: pass

def main(htmlReport):
    
    if htmlReport==None: return
    
    selectedLines = []
    with open(htmlReport, "r") as report:
        lines = report.readlines()
    
    for lineCount, line in enumerate(lines):
        if line.strip().startswith("<u>Electric Lighting Use:</u>"):
            break
            
    for line in lines[lineCount+1:]:
        if line.startswith("<li>"):
            report = line.strip("<li>")[:-6]
            selectedLines.append(report)
        elif line.startswith("</ul>"):
            break
    
    return selectedLines

electricLightingUse = main(_htmlReport)